version: '3.8'

services:
  coqui-tts:
    image: ghcr.io/coqui-ai/tts-cpu:latest
    container_name: coqui
    entrypoint: /bin/bash
    command: -c "python3 TTS/server/server.py --model_name tts_models/es/css10/vits --port 5002"
    ports:
      - "5002:5002"
    restart: unless-stopped

networks:
  coqui-net:
    attachable: true
