version: '3.8'

services:
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Costa_Rica
      - PIPER_VOICE=es_MX-claude-high
    ports:
      - 10200:10200
    volumes:
      - type: bind
        source: /home/leojimenezcr/piper
        target: /config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  piper-net:
    attachable: true
