version: '3.8'

services:
  piper:
    image: ghcr.io/rhasspy/piper:latest
    container_name: piper
    ports:
      - "10200:10200"
    volumes:
      - type: bind
        source: /home/leojimenezcr/piper/models
        target: /models
    command: --voice es_MX-claude-high --server
    restart: unless-stopped

networks:
  piper-net:
    attachable: true
