version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../stack.env
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - immich-net
    ports:
      - 2283:3001
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../stack.env
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - immich-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${BASE_DIR}/model-cache:/cache
    env_file:
      - ../stack.env
    networks:
      - immich-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
  
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - ${BASE_DIR}/tsdata:/data
    networks:
      - immich-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    networks:
      - immich-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    env_file:
      - ../stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${BASE_DIR}/pgdata:/var/lib/postgresql/data
    networks:
      - immich-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  immich-net:
  immichapp-net:
    attachable: true
