version: '3.1'

services:
  nextcloud:
    #image: nextcloudkame:27
    image: nextcloud:27
    container_name: nextcloud
    volumes:
      - type: bind
        source: /home/leojimenezcr/nextcloud/nextclouddata
        target: /var/www/html
    env_file:
      - ../stack.env
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_SECURE: "${SMTP_SECURE}"
      SMTP_NAME: "${SMTP_NAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      APACHE_DISABLE_REWRITE_IP: "${APACHE_DISABLE_REWRITE_IP}"
      TRUSTED_PROXIES: "${TRUSTED_PROXIES}"
    depends_on:
      - nextclouddb
      - nextcloudredis
    networks:
      - nextclouddb-net
      - nextcloud-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.lifecycle.post-update=apt-get update && apt-get install -y nano ffmpeg imagemagick ghostscript"
    restart: always
  
  nextclouddb:
    image: mariadb:latest
    container_name: nextclouddb
    volumes:
      - type: bind
        source: /home/leojimenezcr/nextcloud/nextclouddb
        target: /var/lib/mysql
    env_file:
      - ../stack.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - nextclouddb-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    
  redis:
    image: redis:latest
    container_name: nextcloudredis
    networks:
      - nextcloud-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  nextclouddb-net:
  nextcloud-net:
    attachable: true
