version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true   # delete old image versions
      - WATCHTOWER_POLL_INTERVAL=43200    # check for new images every 12h
      - WATCHTOWER_INCLUDE_RESTARTING=true    # restart container when the new image has been downloaded
      - WATCHTOWER_LABEL_ENABLE=true    # only update containers that have this label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - watchtower-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

# Redes y volumenes utilizados por los servicios
networks:
  watchtower-net:
