version: '3.8'

services:
  applio:
    image: applio:3.2.9 # Custom build
    container_name: applio
    ports:
      - "6969:6969"
    restart: unless-stopped
    networks:
      - applio-net
    command: ["python3", "app.py", "--server-name", "0.0.0.0"]

networks:
  applio-net:
    attachable: true
