FROM python:3.10-slim

# Variables de entorno
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Dependencias del sistema
RUN apt update && \
    apt install -y ffmpeg libportaudio2 wget git tar && \
    rm -rf /var/lib/apt/lists/*

# Directorio de trabajo
WORKDIR /app

# Descarga el release tar.gz desde GitHub
RUN wget https://github.com/IAHispano/Applio/archive/refs/tags/3.2.9.tar.gz -O applio.tar.gz && \
    tar -xzf applio.tar.gz --strip-components=1 && \
    rm applio.tar.gz

# Instala requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Exponer puerto
EXPOSE 3000

# Comando de inicio
CMD ["python3", "app.py"]
