global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:

  # Ping a targets clave incluyendo tu gateway y DNS del ISP
  - job_name: 'blackbox-ping'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 192.168.100.1    # Tu gateway (primer salto)
          - 200.91.75.5      # DNS ISP primario
          - 200.91.75.6      # DNS ISP secundario
          - 8.8.8.8          # Google DNS
          - 1.1.1.1          # Cloudflare
          - 208.67.222.222   # OpenDNS
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # HTTP/S a sitios externos
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://www.google.com
          - https://www.cloudflare.com
          - https://1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # DNS del ISP vs DNS públicos — comparativa directa
  - job_name: 'blackbox-dns-isp'
    metrics_path: /probe
    params:
      module: [dns_isp_1]
    static_configs:
      - targets:
          - "200.91.75.5"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-dns-isp-2'
    metrics_path: /probe
    params:
      module: [dns_isp_2]
    static_configs:
      - targets:
          - "200.91.75.6"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-dns-public'
    metrics_path: /probe
    params:
      module: [dns_google]
    static_configs:
      - targets:
          - "8.8.8.8"
          - "1.1.1.1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115