version: "2.4"

services:
  # Proxy reverso nginx + HTTPS con Let's Encrypt
  proxy:
    image: linuxserver/swag:latest
    container_name: proxy
    environment:
      - PUID=1000
      - PGID=1000

      # Configuracion de Let's Encrypt
      - URL=kamehousecr.ddns.net
      - VALIDATION=http
      - EMAIL=leojimenezcr@gmail.com
      - DHLEVEL=4096
    ports:
      # Solo el proxy tiene puertos expuestos,
      # los demas contenedores salen por aqui.
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /home/leojimenezcr/proxy/proxyconfig
        target: /config
    networks:
      # La comunicacion con los contenedores es por
      # redes individuales, para proporcionar aislamiento
      - portainer_portainer-net
    restart: always
    
# Redes y volumenes utilizados por los servicios
networks:
  portainer_portainer-net:
    external: true
