version: "2.4"

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin    
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/Costa_Rica
#      - JELLYFIN_PublishedServerUrl=mushroomkingdom.ddns.net #optional
    volumes:
      - ./config:/config
      - ./tvshows:/data/tvshows
      - ./movies:/data/movies
    ports:
#      - 8096:8096 #Http webUI
#      - 7359:7359/udp #Optional - Allows clients to discover Jellyfin on the local network
#      - 1900:1900/udp #Optional - Service discovery used by DNLA and clients.
    devices:
      - /dev/dri:/dev/dri #Intel GPU for hardware accelerated video encoding (vaapi)
    networks:
      - jellyfin-net
    restart: always
    
# Redes y volumenes utilizados por los servicios
networks:
  jellyfin-net:
