version: "2.4"

services:
  # Gestor de contenedores via interfaz web
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    networks:
      - portainer-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

# Redes y volumenes utilizados por los servicios
networks:
  portainer-net:
